### ISSUE TITLE
Crash of v3.0-oss

### ISSUE THREAD

**Issue by ddelaqua** [oliexdev/openScale#1156]
**Describe the bug**
Installing version 3.0-oss made the app unusable. I can't launch it at all.
When I select the app, the "Overview" screen appears with the information "No user active" and the app closes immediately. 

**To Reproduce**
1. Just start the app 
2. See error

Reproduced with v3.0-oss from Google Play Store

**Expected behavior**
The app starts using previous data 

**Additional context**
I cleared the cache, but the app still won't open.
I didn't clear the entire memory because I dond't have back up the data...

**Debug log**
I can't generate the log

**Comment by ddelaqua** [comment]
**Updating:**
I downgraded to v2.5.4 and when I started it, there was no data in the app. Apparently v3.0 made the database unusable... 
So I formatted all v3.0 storage (memory and cache) and the app started, however, also without any data

I found an old backup and when I selected the file I got the following message: _Restore failed: Essential database files not found in the backup._

**Comment by oliexdev** [comment]
Thanks for reporting, the database was changed completely in openScale 3.0, I have to write a migration implementation. Do you have the old openScale version installed? Then please export your data into a CVS file and try to import it in the new openScale 3.0.

**Comment by ddelaqua** [comment]
Thanks for the reply.
I reinstalled by downloading version 2.5.4 from Github because the update to 3.0 from Google Play overwrote the previous version. However, when I go to _"Settings > Backup > Export Backup"_ there's no option to select the CSV extension. It automatically exports as a .DB file. How do I export as a CSV file?

Another question: automatic backups had apparently been disabled, but I don't understand why. So, the last backup I have is from March 2025. Is there any way to recover more recent data? Perhaps directly from a folder?

**EDIT 1:** I found how to export the CSV spreadsheet. I exported it in v2.5.4 (Github) and tried to import it in version 3.0 (Google Play) and got the following messages: 
_Import failed: The mandatory column date is missing in the CSV header._
and
_No valid data found in the CSV file, or all rows contained errors_

**Comment by oliexdev** [comment]
you have to change the column names in the CSV file from openScale 2.x
```
"biceps","bone","caliper1","caliper2","caliper3","calories","chest","comment","dateTime","fat","hip","lbm","muscle","neck","thigh","visceralFat","waist","water","weight"
0.0,0.0,0.0,0.0,0.0,0.0,0.0,"","2025-08-12 06:12",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0
```
to openScale 3.x
```
DATE,TIME,BICEPS,BMI,BMR,BODY_FAT,BONE,CALIPER,CALIPER_1,CALIPER_2,CALIPER_3,CALORIES,CHEST,COMMENT,HIPS,LBM,MUSCLE,NECK,TDEE,THIGH,VISCERAL_FAT,WAIST,WATER,WEIGHT,WHR,WHTR
2025-08-12,06:29:31.715,,0.88,,,,,,,,,,,,,,,,,,,,3.0,,
```

Important ist to change column name "dateTime" to date and to format the old dateTime column only to '2025-08-12' format without the time.
I need to improve this to accept also the old format.

**Comment by oliexdev** [comment]
with the latest beta on GitHub you can import your old CSV file, I made a fix to allow the old column name dateTime.

**Comment by TheRedWolf** [comment]
Got the same crash on upgrade, cleared cache but still crashes. Is there a recommended recovery path at this stage?

**Comment by oliexdev** [comment]
You have to deinstall the beta app and install it again.

**Comment by TheRedWolf** [comment]
> You have to deinstall the beta app and install it again.

Uninstalled and reinstalled v3.0-oss but I'm still getting crashes. Presumably it's having trouble with thr local database?

**Comment by oliexdev** [comment]
Strange could you double check if you really removed the old app?

**Comment by TheRedWolf** [comment]
Same outcome when uninstalling and reinstalling via the Play store. I'm not clearing the app data though, which I presume is being preserved across installations.

Interestingly the last backup is from some days ago too, not sure why the last few days are missing. Ideally I'd like to get the data from the old database if I can, but at worst I'll wear four or so days lost...

**Comment by oliexdev** [comment]
Can you give a step by step what you did?

Which openScale versions do you have installed?

If you have installed the beta version of openScale (did you receive an invitation?) this beta should be parallel installed by any other openScale version which you may have installed before.

Did you removed the other openScale version after you installed the beta version?

**Comment by TheRedWolf** [comment]
Currently only v3.0-oss installed, along with openScale sync 0.4.2-oss. No other versions installed.

Definitely have the beta version installed, I believe the previous version installed was 2.5.4, but I'm not sure as it updated via the Play store to 3.0. As I recall there was a relatively recent update to it, maybe a few weeks ago?

Whichever one it was, I believe it was one version short of the one required to trigger automatic syncing, as ai had to run full syncs every few days.

**Comment by oliexdev** [comment]
ok then I am bit lost why it won't start. You have to full remove the openScale oss version because in v3.0 the database structure is different. They have to initialized again the database from scratch of course the old database will be destroyed.

**Comment by ddelaqua** [comment]
**Update:**
I edited the .csv file containing the data from the last backup (I've accepted that I unfortunately lost a lot of measurements...).
I organized the columns as you mentioned in the comment (since it wasn't very clear, I assumed the date format is "yyyy/mm/dd").
I'm not a programmer, but I understand spreadsheets, so there was a little manual work involved. Unfortunately, I can't help automate the export to contribute to the project.
The OpenScale v3.0 (remember, my version is the Google Play version) imported the .csv file without any problems.

**I have other things to report.**
1. An error is occurring when synchronizing with the scale.
When I access the _"Settings > Bluetooth > Search for Scales"_ menu, the app finds my scale, a Xiaomi Mi Body Composition Scale 2, which is registered as "MIBFS." However, when I try to sync, a message appears in a red banner saying **_"Driver for MIBFS not found or internal error."_** This error appears even after completely clearing the app's data, with or without importing the data from the .csv file.

2. When registering a user, when we enter a birthday, the app records the day before the selected date. For example, if we select 01/01/1990 (mm/dd/yyyy), the app will display the date 12/31/1989. This happens whether the date is selected from the calendar or typed in. I don't know if it has to do with the smartphone's date format, as the default format in my region is (dd/mm/yyyy).

3. In _"Edit Measurement"_ I can't change the user who owns the measurement. This property is very interesting when two users have similar measurements.

4. In the _"Overview"_ tab, the graphs don't have the y-axis display option and aren't dynamic like in previous versions, when the space they occupied changed as more data was selected to display.

I apologize if this is a lot of cluttered feedback. If you think it's better, let me know and I'll create "New Issues" for each topic.


**EDIT**
I'm running in a Samsung A54 with One UI 7.0 and Android 15

> you have to change the column names in the CSV file from openScale 2.x
> 
> ```
> "biceps","bone","caliper1","caliper2","caliper3","calories","chest","comment","dateTime","fat","hip","lbm","muscle","neck","thigh","visceralFat","waist","water","weight"
> 0.0,0.0,0.0,0.0,0.0,0.0,0.0,"","2025-08-12 06:12",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80.0
> ```
> 
> to openScale 3.x
> 
> ```
> DATE,TIME,BICEPS,BMI,BMR,BODY_FAT,BONE,CALIPER,CALIPER_1,CALIPER_2,CALIPER_3,CALORIES,CHEST,COMMENT,HIPS,LBM,MUSCLE,NECK,TDEE,THIGH,VISCERAL_FAT,WAIST,WATER,WEIGHT,WHR,WHTR
> 2025-08-12,06:29:31.715,,0.88,,,,,,,,,,,,,,,,,,,,3.0,,
> ```
> 
> Important ist to change column name "dateTime" to date and to format the old dateTime column only to '2025-08-12' format without the time. I need to improve this to accept also the old format.

**Comment by oliexdev** [comment]
> **Update:** I edited the .csv file containing the data from the last backup (I've accepted that I unfortunately lost a lot of measurements...). I organized the columns as you mentioned in the comment (since it wasn't very clear, I assumed the date format is "yyyy/mm/dd"). I'm not a programmer, but I understand spreadsheets, so there was a little manual work involved. Unfortunately, I can't help automate the export to contribute to the project. The OpenScale v3.0 (remember, my version is the Google Play version) imported the .csv file without any problems.

Did you transfer all yours measurements into the beta app? The beta app was released only for a couple of weeks. Which openScale version did you use before and is this still installed?

> **I have other things to report.**
> 
> 1. An error is occurring when synchronizing with the scale.
>    When I access the _"Settings > Bluetooth > Search for Scales"_ menu, the app finds my scale, a Xiaomi Mi Body Composition Scale 2, which is registered as "MIBFS." However, when I try to sync, a message appears in a red banner saying **_"Driver for MIBFS not found or internal error."_** This error appears even after completely clearing the app's data, with or without importing the data from the .csv file.

Could you turn on the logging while this error occured in Settings->General->File Logging and post the result here 

> 2. When registering a user, when we enter a birthday, the app records the day before the selected date. For example, if we select 01/01/1990 (mm/dd/yyyy), the app will display the date 12/31/1989. This happens whether the date is selected from the calendar or typed in. I don't know if it has to do with the smartphone's date format, as the default format in my region is (dd/mm/yyyy).

Can't reproduce this error here. On which screen are you talking about the wrong date is being displayed? On the settings->user edit mode?

> 4. In _"Edit Measurement"_ I can't change the user who owns the measurement. This property is very interesting when two users have similar measurements.

This is currently not implemented in the beta version.

> 6. In the _"Overview"_ tab, the graphs don't have the y-axis display option and aren't dynamic like in previous versions, when the space they occupied changed as more data was selected to display.> > I apologize if this is a lot of cluttered feedback. If you think it's better, let me know and I'll create "New Issues" for each topic.

What do you mean by that? You can filter the time range which will be shown on the top right filter icon.

> **EDIT** I'm running in a Samsung A54 with One UI 7.0 and Android 15
>

**Comment by ddelaqua** [comment]
> Did you transfer all yours measurements into the beta app? The beta app was released only for a couple of weeks. Which openScale version did you use before and is this still installed?

I was using v2.5.4-oss, which I had installed through Google Play Store and the app was recently updated to v3.0-oss (67). This update destroyed the database.

So I installed v2.5.4 (66) (downloaded from Github), imported the last saved database (which, as I mentioned, was outdated), exported the .csv file from the "Table" tab, separated the DATE and TIME values, and changed the order of the data, organizing it as you described (this process was manual using a spreadsheet). 
Then imported the .csv file into v3.0-oss (67) (Google Play Store update).

So, now I currently have v3.0-oss (67) (Google Play Store) and v2.5.4 (66) (Github) installed.

> Could you turn on the logging while this error occured in Settings->General->File Logging and post the result here

I turned on File Logging but now I can't sync. As soon as I can, I'll edit it here.
**EDIT1**
The log:
[openScale_current_log.txt](https://github.com/user-attachments/files/21744719/openScale_current_log.txt)
**EDIT2**
I don't know why the log didn't save the Bluetooth sync attempt... I'm sending a new log
[openScale_current_log2.txt](https://github.com/user-attachments/files/21746372/openScale_current_log2.txt)

> Can't reproduce this error here. On which screen are you talking about the wrong date is being displayed? On the settings->user edit mode?

Sorry for not being clear. The problem is in v3.0-oss (67) "Settings > User" in both "Add User" and "Edit User" under the "Birth Date" option.
This one-day difference is irrelevant to the calculations, but it was something I identified.

In the example below I select the date 01/01/1990
![Image](https://github.com/user-attachments/assets/b35f0496-4e76-408b-b387-f888a05dcd42)

However, when I click "Ok", the date in the "Birth Date" field appears as 12/31/1989 (remembering that the date standard for my region is dd/mm/yyyy)
![Image](https://github.com/user-attachments/assets/fa08c568-98e5-459c-a0e5-0dd42cf75123)

> This is currently not implemented in the beta version.

Ok, sure

> What do you mean by that? You can filter the time range which will be shown on the top right filter icon.

The Y-axis. In fact, selecting which side of the axis the measurement is represented on (as in v2.5.4) is interesting for very distant measurements, such as kg and %, for example.
![Image](https://github.com/user-attachments/assets/9f7dcaf9-4fc1-460a-be07-f5b8473327b6)

An example of how selecting the data makes the graph adjust how it fills the screen,
when we select only water
![Image](https://github.com/user-attachments/assets/b6ba54e1-c2eb-4066-ae44-879d88100994)

 and water+muscle data
![Image](https://github.com/user-attachments/assets/e1b7bd3b-d105-4afe-8449-d9ac63db488a)

**Comment by oliexdev** [comment]
> > Could you turn on the logging while this error occured in Settings->General->File Logging and post the result here
> 
> I turned on File Logging but now I can't sync. As soon as I can, I'll edit it here. **EDIT1** The log: [openScale_current_log.txt](https://github.com/user-attachments/files/21744719/openScale_current_log.txt) **EDIT2** I don't know why the log didn't save the Bluetooth sync attempt... I'm sending a new log [openScale_current_log2.txt](https://github.com/user-attachments/files/21746372/openScale_current_log2.txt)

Thanks for your logs, it should be fixed with commit https://github.com/oliexdev/openScale/commit/e5e670835a23872d0caf32784ed2b5feb9f12d4d

> > Can't reproduce this error here. On which screen are you talking about the wrong date is being displayed? On the settings->user edit mode?
> 
> Sorry for not being clear. The problem is in v3.0-oss (67) "Settings > User" in both "Add User" and "Edit User" under the "Birth Date" option. This one-day difference is irrelevant to the calculations, but it was something I identified.

Thanks for the hint, it should be fixed with commit https://github.com/oliexdev/openScale/commit/aa7a92394667f3ebf51d3d1cba262ef70e50b656

> > What do you mean by that? You can filter the time range which will be shown on the top right filter icon.
> 
> The Y-axis. In fact, selecting which side of the axis the measurement is represented on (as in v2.5.4) is interesting for very distant measurements, such as kg and %, for example. 
> 

Now I understand what you mean, yeah this is currently not implemented in the beta version.

**Comment by TheRedWolf** [comment]
Got around to firing up adb to dump a crash log of openScale v3.0 on my phone... I've uninstalled and reinstalled it a few times but it would appear the original datafile stays in place, based on the following:

`08-13 18:27:13.369  2086  2145 I SQLiteOpenHelper: DB version downgrading from 6 to 1
08-13 18:27:13.371  2086  2148 I SQLiteOpenHelper: DB version downgrading from 6 to 1
--------- beginning of crash
08-13 18:27:13.376  2086  2132 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
08-13 18:27:13.376  2086  2132 E AndroidRuntime: Process: com.health.openscale.oss, PID: 2086
08-13 18:27:13.376  2086  2132 E AndroidRuntime: java.lang.IllegalStateException: A migration from 6 to 1 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* functions.
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.BaseRoomConnectionManager.onMigrate(RoomConnectionManager.kt:221)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.RoomConnectionManager$SupportOpenHelperCallback.onUpgrade(RoomConnectionManager.android.kt:152)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.RoomConnectionManager$SupportOpenHelperCallback.onDowngrade(RoomConnectionManager.android.kt:160)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onDowngrade(FrameworkSQLiteOpenHelper.android.kt:269)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:517)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:419)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.android.kt:224)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.android.kt:180)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.android.kt:141)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.android.kt:96)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.driver.SupportSQLiteDriver.open(SupportSQLiteDriver.android.kt:26)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.driver.SupportSQLiteConnectionPool.getSupportConnection(SupportSQLiteConnectionPool.android.kt:35)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.driver.SupportSQLiteConnectionPool.useConnection(SupportSQLiteConnectionPool.android.kt:42)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.RoomConnectionManager.useConnection(RoomConnectionManager.android.kt:126)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.RoomDatabase.useConnection$room_runtime_release(RoomDatabase.android.kt:593)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$$inlined$compatCoroutineExecute$DBUtil__DBUtil_androidKt$1.invokeSuspend(DBUtil.android.kt:113)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.android.kt:38)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.TransactionExecutor.$r8$lambda$FZWr2PGmP3sgXLCiri-DCcePXSs(Unknown Source:0)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1119)
08-13 18:27:13.376  2086  2132 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ddcb05, Dispatchers.IO]`

Is there any particular reason we couldn't have the old version of database from 2.5.x upgraded to the schema/format used in v3 if the app can detect it has an old version of database present?

At minimum I'd love a way to get the actual SQLite database out of the device, unfortunately it's hidden away in the data directory and I can't get to it through any conventional means... If I could, I could upgrade the schema manually and reinject it with all data intact...

**Comment by oliexdev** [comment]
> > What do you mean by that? You can filter the time range which will be shown on the top right filter icon.
> 
> The Y-axis. In fact, selecting which side of the axis the measurement is represented on (as in v2.5.4) is interesting for very distant measurements, such as kg and %, for example. 

I implemented that but make sure you exported you data before because you have to reinstalled the whole app again (the app database was changed)

@TheRedWolf 
> Got around to firing up adb to dump a crash log of openScale v3.0 on my phone... I've uninstalled and reinstalled it a few  times but it would appear the original datafile stays in place, based on the following:

How do you uninstall the app? It is strange that they don't delete the database then? Do you have another openScale version installed? If you install the openScale version 2.x maybe then the database will be open?

**Comment by TheRedWolf** [comment]
> How do you uninstall the app? It is strange that they don't delete the database then? Do you have another openScale version installed? If you install the openScale version 2.x maybe then the database will be open?

I uninstall it through the play store.

Definitely no other versions installed. I did try installing the github apk for 2.5.4 but it uses a different identifier, the play store version is com.health.openscale.oss while the github version uses com.health.openscale, so they don't use the same datafile

**Comment by oliexdev** [comment]
> efinitely no other versions installed. I did try installing the github apk for 2.5.4 but it uses a different identifier, the play store version is com.health.openscale.oss while the github version uses com.health.openscale, so they don't use the same datafile

Please try to uninstall not via GooglePlay just press long on the icon and the move it to the uninstall field.

**Comment by TheRedWolf** [comment]
> 
> Please try to uninstall not via GooglePlay just press long on the icon and the move it to the uninstall field.

Not sure I've tried this, but in any case I still want to recover and work with the old database rather than nuking it entirely, as the old version of the app missed about four or five days of measurements by doing its last backup on 08/08.

I'm confident I could build local scripts to handle upgrading the database but first I need to be able to get to it, which is proving difficult given v3.0-oss won't handle it and no other versions I've got attempts to use com.health.openscale.oss.

At this stage I'm thinking I'll need to pull a copy of the 2.5.4 source code and see if I can edit it to use the .oss bit and compile it myself. If that works it should get me access to the original database which I can then export.

Not being a mobile app dev I'm not quite sure where to start or the ramifications of doing the above... though before v3 gets released to the world I do think having a built-in means to upgrade the database is key for good UX. Most users won't want to have to export and reimport their data manually if they upgrade...

**Comment by TheRedWolf** [comment]
Even with mucking around with the old version custom compiled, it seems my data is gone... To that end I've given up and accepted the loss of the last week's worth of data and have instead tried figuring out how to push the contents of old backup files into the new database format. So far I've got a nice little python script which can take entries from the old database format and get them into the new one, but I'm having some trouble with the BMR value which is typically derived from existing weight, height and age measurements.

In v3.0 I have the profile set up correctly with my age, and I've loaded my imported database into the application without issue (the imported data shows as expected too!)

The problem arises when I edit an existing record, then save it to get the derived values (BMR, TDEE, BMI, etc) to generate. BMI generates as expected, but BMR seems to be off by about 142 from what I expected it to be, and even running the calculation manually I still get a value different to that displayed in the app. TDEE being derived from BMR is correct for the BMR value, but given the BMR value is apparently incorrect, so is TDEE as a result.

**Comment by TheRedWolf** [comment]
For anyone who might find it helpful, here's the python script I mentioned earlier. It can be extended to include additional values, but things like BMR, BMI and TDEE are all derived values which need to be calculated in-flight to generate the entries for MeasurementValue.

To use, you'll need to set up v3.0 and configure the user profile, then back up the new database. Grab the backed up database (zip file), pull it down to your PC and unzip it to get the openScale.db (and db-shm and db-wal files). v2.5.4 generates backup files as a sqlite .db file, copy it down locally too and make sure it has a different file name. Run the script with python3.7 after setting the source and destination database filenames.

This script assumes you've got an empty destination database, so keep this in mind as there's no integrity checking or anything to handle duplicate entries. I've tested it with my own dataset (about 850 records) with no problems on the import, apart from the missing derived values.


```
import sqlite3


SOURCE_DB = "old_openScale.db"       # Path to source database
DEST_DB = "new_openScale.db"    # Path to destination database

def main():
    # Connect to source and destination databases
    src_conn = sqlite3.connect(SOURCE_DB)
    dest_conn = sqlite3.connect(DEST_DB)
    
    src_cur = src_conn.cursor()
    dest_cur = dest_conn.cursor()

    # Select only rows with enabled = 1
    src_cur.execute("""
        SELECT id, userId, enabled, datetime, weight, fat, water, muscle, 
               visceralFat, lbm, waist, hip, bone, chest, thigh, biceps, 
               neck, caliper1, caliper2, caliper3, calories, comment
        FROM scaleMeasurements
        WHERE enabled = 1
    """)
    
    rows = src_cur.fetchall()

    # Start transaction on destination DB
    dest_conn.execute("BEGIN TRANSACTION;")

    for row in rows:
        (
            id_val, user_id, enabled, timestamp, weight, fat, water, muscle,
            visceral_fat, lbm, waist, him, bone, chest, thigh, biceps, neck,
            cal1, cal2, cal3, calories, comment
        ) = row

        # Insert into Measurement table
        dest_cur.execute("""
            INSERT INTO Measurement (id, userId, timestamp)
            VALUES (?, ?, ?)
        """, (id_val, user_id, timestamp))

        # Define mapping of source values to typeId
        measurement_map = [
            (1, weight),
            (3, fat),
            (4, water),
            (5, muscle),
            (6, lbm),
            (7, bone)
        ]

        # Insert each mapped value into MeasurementValue
        for type_id, value in measurement_map:
            dest_cur.execute("""
                INSERT INTO MeasurementValue
                (measurementId, typeId, floatValue, intValue, textValue, dateValue)
                VALUES (?, ?, ?, NULL, NULL, NULL)
            """, (id_val, type_id, value))

        # Show the row in the console before moving on
        for col, val in zip(
            ["id", "userId", "enabled", "datetime", "weight", "fat", "water",
             "muscle", "visceralFat", "lbm", "waist", "him", "bone", "chest",
             "thigh", "biceps", "neck", "caliper1", "caliper2", "caliper3",
             "calories", "comment"], row):
            print(f"{col}: {val}")
        print("-" * 40)
        # input("Press Enter for next row...")

    # Commit all changes once at the end
    dest_conn.commit()

    # Close connections
    src_conn.close()
    dest_conn.close()

if __name__ == "__main__":
    main()
```

**Comment by oliexdev** [comment]
> In v3.0 I have the profile set up correctly with my age, and I've loaded my imported database into the application without issue (the imported data shows as expected too!)

great and thanks for the python script.

> The problem arises when I edit an existing record, then save it to get the derived values (BMR, TDEE, BMI, etc) to generate. BMI generates as expected, but BMR seems to be off by about 142 from what I expected it to be, and even running the calculation manually I still get a value different to that displayed in the app. TDEE being derived from BMR is correct for the BMR value, but given the BMR value is apparently incorrect, so is TDEE as a result.

I did a fix with 28725e9ba374bcf02758d2c662798c9fd3420bf8 where the correct internal base unit are used for derived values, you can trigger a recalulation if you change the unit for e.g. the weight measurement type in the settings.

**Comment by ddelaqua** [comment]
In v3.0 (sha256:f5a3e08619847a0f3e7f2aee966acaf6eec6a0c22877f6c7d6fb845ff9b8d01b) whenever I import data from .csv files, on the "Overview" screen the data appears without the units in the list below the graph. So I went to "Settings > Measurements Types" opened one, and select saved it without editing anything, and the following popup appeared: 

![Image](https://github.com/user-attachments/assets/c19ebe3d-9585-409e-a003-663c8df61dde)

After that the unit I saved (without editing anything) shows the unit in the list (%, cm, kg) 

I noticed that the "BMR" and "TDEE" units were missing values after opening and saving in "Measurements Types". I didn't find any issues with the other measurements.

**Comment by oliexdev** [comment]
@ddelaqua Thanks for the hint, I fixed that but you have to delete your database or reinstall the app (make a backup before you do it) to see the changes because they have to initialized the measurement types again.

**Comment by ddelaqua** [comment]
The problem with Date selection that occurred in "Birth Day" also occurs when we edit the measurement Date values in "Edit Measurement" (by clicking on the measurement pencil in "Overview)

Some measurement types in v2.5.4 had formula selection options. Will this be implemented in v3.0? 

A suggestion: the "Table" tab could be moved to "Settings > Data Management"

Things I missed from v2.5.4 to v3.0:
In the "Overview" tab, when I select a point on the graph, the list below the graph automatically goes to the day I selected. This is very useful when I identify an incorrect value by reading the graph (I'm not the only one who uses the scale).

In the list of measurements in the "Overview" tab, when you clicked on a measurement, a horizontal bar with "reference values" expanded. I think these metrics are cool to track. Even if the user does not expand to see the horizontal bar, next to the values are vertical bars that change colors according to the measurement, depending on whether the user is below, above or within normal limits.

**Comment by oliexdev** [comment]
> The problem with Date selection that occurred in "Birth Day" also occurs when we edit the measurement Date values in "Edit Measurement" (by clicking on the measurement pencil in "Overview)

Should be fixed
 
> Some measurement types in v2.5.4 had formula selection options. Will this be implemented in v3.0?

Do you mean those https://github.com/oliexdev/openScale/wiki/Body-metric-estimations
 
> A suggestion: the "Table" tab could be moved to "Settings > Data Management"

Why?

> Things I missed from v2.5.4 to v3.0: In the "Overview" tab, when I select a point on the graph, the list below the graph automatically goes to the day I selected. This is very useful when I identify an incorrect value by reading the graph (I'm not the only one who uses the scale).

Implemented in the latest beta build

> In the list of measurements in the "Overview" tab, when you clicked on a measurement, a horizontal bar with "reference values" expanded. I think these metrics are cool to track. Even if the user does not expand to see the horizontal bar, next to the values are vertical bars that change colors according to the measurement, depending on whether the user is below, above or within normal limits.

Yes will definitly come but it is currently on my ToDo list.

**Comment by oliexdev** [comment]
> > In the list of measurements in the "Overview" tab, when you clicked on a measurement, a horizontal bar with "reference values" expanded. I think these metrics are cool to track. Even if the user does not expand to see the horizontal bar, next to the values are vertical bars that change colors according to the measurement, depending on whether the user is below, above or within normal limits.
> 
> Yes will definitly come but it is currently on my ToDo list.

Now it is implemented in the latest beta build

**Comment by ddelaqua** [comment]
> > Some measurement types in v2.5.4 had formula selection options. Will this be implemented in v3.0?
> 
> Do you mean those https://github.com/oliexdev/openScale/wiki/Body-metric-estimations

Exactly

> > A suggestion: the "Table" tab could be moved to "Settings > Data Management"
> 
> Why?

Sorry, this is such incomplete feedback. My suggestion is to move the "Table" to "Settings > Data Management" because, based on my experience with the app, the table is used to read the recorded data and make minor adjustments if necessary. It's practically useless for analyzing historical progress.
For analysis, reading the graphs is best.
Of course, this is my personal experience.
Perhaps just adjusting the menu order would be interesting. Here's a suggestion:
Overview
Charts
Statistics
Table
Settings

> > Things I missed from v2.5.4 to v3.0: In the "Overview" tab, when I select a point on the graph, the list below the graph automatically goes to the day I selected. This is very useful when I identify an incorrect value by reading the graph (I'm not the only one who uses the scale).
> 
> Implemented in the latest beta build

I noticed a slight slowdown in the animation when the "All Days" view is selected, but it worked perfectly going to the date, thanks

> > In the list of measurements in the "Overview" tab, when you clicked on a measurement, a horizontal bar with "reference values" expanded. I think these metrics are cool to track. Even if the user does not expand to see the horizontal bar, next to the values are vertical bars that change colors according to the measurement, depending on whether the user is below, above or within normal limits.
> 
> Yes will definitly come but it is currently on my ToDo list.

The style you chose is really great! Thank you so much!

**Comment by ddelaqua** [comment]
@oliexdev 
Hello again!
I'm submitting a new issue I've identified, and regarding this, what do you think about editing the name of this one? "Crash of v3.0-oss" no longer seems relevant to the topic...

The issue in question concerns the syncing of the Mi Body Composition Scale 2.
I've been trying to sync, but it hasn't been as straightforward as in the previous version.
In v2.5.4, I usually do the following: 1. Keep Bluetooth syncing disabled in the app; 2. Step on the scale and take the measurement normally; 3. Step off the scale; 4. Turn Bluetooth syncing on.
By doing this, the "Overview" tab updated all measurements, both the one I'd just taken and previous ones that hadn't synced.

Today I tried the same thing with v3.0, but I couldn't sync. The app showed notifications in the footer, but the measurements didn't sync. I generated the log below.
[openScale_current_log.txt](https://github.com/user-attachments/files/21856050/openScale_current_log.txt)


I synced with v2.5.4 and the app read all data.

Another issue is that the "Muscle" data has been registering very high values (near 70%). This has been happening since v2.5.4 and continues in v3.0. I hadn't noticed it before, but with yesterday's update on the "reference values," I noticed this issue.

**Comment by oliexdev** [comment]
> [@oliexdev](https://github.com/oliexdev) Hello again! I'm submitting a new issue I've identified, and regarding this, what do you think about editing the name of this one? "Crash of v3.0-oss" no longer seems relevant to the topic...

no its ok.

> The issue in question concerns the syncing of the Mi Body Composition Scale 2. I've been trying to sync, but it hasn't been as straightforward as in the previous version. In v2.5.4, I usually do the following: 1. Keep Bluetooth syncing disabled in the app; 2. Step on the scale and take the measurement normally; 3. Step off the scale; 4. Turn Bluetooth syncing on. By doing this, the "Overview" tab updated all measurements, both the one I'd just taken and previous ones that hadn't synced.
> 
> Today I tried the same thing with v3.0, but I couldn't sync. The app showed notifications in the footer, but the measurements didn't sync. I generated the log below. [openScale_current_log.txt](https://github.com/user-attachments/files/21856050/openScale_current_log.txt)
> 
> I synced with v2.5.4 and the app read all data.
> 
> Another issue is that the "Muscle" data has been registering very high values (near 70%). This has been happening since v2.5.4 and continues in v3.0. I hadn't noticed it before, but with yesterday's update on the "reference values," I noticed this issue.

Please try out the latest beta build. If it not working please post the full log file

**Comment by ddelaqua** [comment]
> > The issue in question concerns the syncing of the Mi Body Composition Scale 2. I've been trying to sync, but it hasn't been as straightforward as in the previous version. In v2.5.4, I usually do the following: 1. Keep Bluetooth syncing disabled in the app; 2. Step on the scale and take the measurement normally; 3. Step off the scale; 4. Turn Bluetooth syncing on. By doing this, the "Overview" tab updated all measurements, both the one I'd just taken and previous ones that hadn't synced.
> > Today I tried the same thing with v3.0, but I couldn't sync. The app showed notifications in the footer, but the measurements didn't sync. I generated the log below. [openScale_current_log.txt](https://github.com/user-attachments/files/21856050/openScale_current_log.txt)
> > I synced with v2.5.4 and the app read all data.
> > Another issue is that the "Muscle" data has been registering very high values (near 70%). This has been happening since v2.5.4 and continues in v3.0. I hadn't noticed it before, but with yesterday's update on the "reference values," I noticed this issue.
> 
> Please try out the latest beta build. If it not working please post the full log file

I tried the latest build and the sync issue persists. I'm sending the log
[openScale_current_log.txt](https://github.com/user-attachments/files/21873707/openScale_current_log.txt)

**Comment by oliexdev** [comment]
thanks please try out the latest beta verison

**Comment by ddelaqua** [comment]
After the latest version of v3.0, I no longer had any sync issues. I've been testing it for the last two days, stepping on the scale, measuring, and then initiating the sync process. The app seamlessly syncs all measurements that hadn't been synced before.

One issue I encountered was with the "Visceral Fat" measurement, which displayed the following message where the reference values ​​should be: "No evaluation possible: No matching age band at the time of measurement."

I noticed a difference in the "Visceral Fat" and "Muscle" measurements taken between openScale and the official app for my Mi Body Composition Scale 2 (Zepp), but this apparently relates to a specific scale or method used.

**Comment by oliexdev** [comment]
Yeah the visceral fat and muscle could be slightly differnent than the vendors app. Btw could you test the latest beta again, I made a huge refactoring in the code, I hope I didn't break anything.

**Comment by ddelaqua** [comment]
I tested again and didn't find any issues.
The syncing process works exactly as it did in v2.5.4: I step on the scale, take the measurement, and then, after stepping off, I activate sync in the app. This way, no issues occur.

My perception is that the animations are slowing down the app. For example, during syncing, several message banners appear and disappear in the footer. A message appears asking about the scale being searched, and even with the scale saved in the settings, with each sync, a message appears stating that MIBFS has been set as a favorite. Messages about the measurements that have been synced also appear. I have a suggestion for this: during syncing, keep a fixed banner in the footer, perhaps with a "loading" icon, with the messages displayed.
Another slowdown is when we select a point on the graph in the "Overview" tab, where the list scrolls to the measurement, but with a lot of data, the scrolling becomes "stuck" and ugly.

Another point I found interesting in v2.5.4 was that when the synchronization was complete, the list in the "Overview" tab scrolled to the top, showing the last measurement.

**Comment by oliexdev** [comment]
Thanks for your feedback I made some improvements please test the latest beta build

**Comment by ddelaqua** [comment]
Today I performed a new sync, and for some reason, it didn't sync on the first try. I had to turn sync on and off (via the Bluetooth icon in the "Overview" tab) a few times.

Since I wasn't expecting any issues, I hadn't enabled logging. I'll try to log it later.

**Comment by oliexdev** [comment]
@ddelaqua could you test the latest beta build again?
I’ve migrated the old Java scale handler to the modern Kotlin handler.

**Comment by ddelaqua** [comment]
> [@ddelaqua](https://github.com/ddelaqua) could you test the latest beta build again? I’ve migrated the old Java scale handler to the modern Kotlin handler.

Of course! I would do it anyway... 😂
This latest version started having sync issues again. I ran the following tests:

1. I stepped on the scale, waited for the measurement to finish, stepped off the scale, waited for it to turn off the display, opened OpenScale, and then clicked the icon that starts syncing in the app;

and

2. I opened the app, clicked the Bluetooth sync icon, stepped on the scale, and took the full measurement (I did it this way based on the manufacturer's app).

Neither method worked. I'm sending the log: [openScale_current_log.txt](https://github.com/user-attachments/files/22117560/openScale_current_log.txt)

**One question:** to avoid having two independent apps, would it be possible to integrate openScale sync into the main app?

I also have to say that the app is increasingly beautiful and fluid.
**Congratulations, and thank you for making it available.**

**Comment by oliexdev** [comment]
Thanks, I have made some fixes please test it again with the latest beta build

**Comment by oliexdev** [comment]
> **One question:** to avoid having two independent apps, would it be possible to integrate openScale sync into the main app?

Sry no, it is intended to have a seperate app for syncing to external service (for privacy reasons) With that you can be absolutely sure that openScale will not transfer any data to the internet because the openScale app don't have any permissions for internet or network (only openScale sync have that).

**Comment by ddelaqua** [comment]
> Thanks, I have made some fixes please test it again with the latest beta build

I just tried and the app failed to import again.
I'm uploading a new log.
[openScale_current_log.txt](https://github.com/user-attachments/files/22127580/openScale_current_log.txt)

**Comment by oliexdev** [comment]
You didn't use the latest beta version of openscale https://github.com/oliexdev/openScale/releases/tag/beta-build

**Comment by ddelaqua** [comment]
I was sure I had updated to the latest version, sorry.
I uninstalled the version I had installed, downloaded it from the link, installed it, and tried to sync again, but again without success.
I'm sending the new log 

[openScale_current_log (1).txt](https://github.com/user-attachments/files/22130799/openScale_current_log.1.txt)

**Comment by oliexdev** [comment]
Thanks for the new log. The connection to your Mi Body Composition Scale (MIBFS) works fine — the app detects it as v2 and initializes correctly.

The log shows no stored history records were returned by the scale (History import done: 0 record(s)). This usually means either:

The scale has no unsynced measurements stored, or a measurement wasn’t actually taken during the sync attempt.

Could you please try again with the latest beta build (I have made only a small fix) open, step on the scale, wait until the weight is stable, and then stay on it for a few seconds? After stepping off, check if the new measurement appears in openScale and, if not, please send that log. And please don't mix the use with the vendor app using the mi scale.

**Comment by ddelaqua** [comment]
Hello again

To avoid any problems, I uninstalled the vendor app before installing the latest version.

I installed the openScale app and restored the backup.
I granted Bluetooth access permission, located the scale, and closed the app.

I took two measurements on the scale. The first was by stepping on it and waiting until the display stopped flashing, so I stepped off and waited until the display went off. Then I took the second measurement, remaining on the scale until the display went off.

Without stepping on the scale, I opened the app and tapped the "Bluetooth" icon on app to begin syncing. The app displayed notifications about access to the scale, but no measurements appeared in the list.

So, I tried taking the measurement by stepping on the scale with the app open and the Bluetooth sync icon activated, but still without success.

As requested, I am sending a new log. 
[openScale_current_log.txt](https://github.com/user-attachments/files/22143597/openScale_current_log.txt)

I need to record that I downloaded the latest version available on the website, but the log shows the same value of the previous version:
> Version | 3.0-beta (68)

**Comment by oliexdev** [comment]
I think I found the bug please try out the latest build again. If its still not work try to reset your scale.

**Comment by ddelaqua** [comment]
> I think I found the bug please try out the latest build again. If its still not work try to reset your scale.

Well, the app read the measurements, however, in the measurement list shown in the "Overview" tab, the LBM measurement started to be showed twice...

![Image](https://github.com/user-attachments/assets/017364f0-6feb-4308-8a88-b6e60eed5a8b)

Another problem I noticed is that the synchronized measurements were not erased from the scale's memory after sync, so whenever I took a new measurement and synchronized it, the app read the new measurement and all previous ones.
I'm sending the log

[openScale_current_log.txt](https://github.com/user-attachments/files/22159653/openScale_current_log.txt)

**Comment by oliexdev** [comment]
Thanks with the double LBM should be fixed in the latest build. 

And yes no measurments are ever deleted on the mi scale, see https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale the last paragraph

**Comment by ddelaqua** [comment]
> Thanks with the double LBM should be fixed in the latest build.
> 
> And yes no measurments are ever deleted on the mi scale, see https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale the last paragraph

I took the measurement and the LBM is no longer duplicating data.
However, the issue with duplicate readings persists...
I removed the batteries from the scale to restart it, but the problem persists.
I'm sending a new log: [openScale_current_log.txt](https://github.com/user-attachments/files/22172896/openScale_current_log.txt)

I installed v2.5.4 of openScale and the app performed the reading without any duplication issues. I even found it strange that when I reinstalled the app, all the information I had before uninstalling it was still there, without me restoring a backup.
